# Generated by Django 2.0.3 on 2018-03-17 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Item Name')),
                ('units', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Allowable Inventory Item',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=250, verbose_name='Item Location')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('cost', models.FloatField(default=0, verbose_name='Unit Cost')),
                ('expiration', models.DateField(verbose_name='Expiration Date')),
                ('vendor', models.CharField(max_length=250)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_waitress.AllowedItems')),
            ],
            options={
                'verbose_name': 'Inventory Item',
            },
        ),
    ]
