# Generated by Django 2.0.3 on 2018-04-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Item Name')),
                ('units', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Allowable Inventory Item',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('note', models.TextField(blank=True, verbose_name='Customer Notes')),
                ('ready', models.BooleanField(default=False, verbose_name='Food Ready')),
            ],
            options={
                'verbose_name': 'Order Item',
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc', models.CharField(max_length=250, verbose_name='Item Location')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('cost', models.FloatField(default=0, verbose_name='Unit Cost')),
                ('expiration', models.DateField(verbose_name='Expiration Date')),
                ('vendor', models.CharField(max_length=250)),
                ('itemType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_waitress.AllowedItems')),
            ],
            options={
                'verbose_name': 'Inventory Item',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuItem', models.CharField(max_length=60)),
                ('menuDescription', models.CharField(max_length=400)),
                ('menuPrice', models.FloatField()),
            ],
            options={
                'verbose_name': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Number',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField()),
                ('ready', models.BooleanField(default=False)),
                ('total', models.FloatField()),
                ('orderNumber', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
        migrations.CreateModel(
            name='RestaurantName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Restaurant Name',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('starRating', models.FloatField()),
                ('review', models.CharField(max_length=250)),
                ('menuItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_waitress.Menu')),
            ],
            options={
                'verbose_name': 'Review',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_waitress.Menu'),
        ),
        migrations.AddField(
            model_name='entry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='virtual_waitress.Order'),
        ),
    ]
