# Generated by Django 2.0.3 on 2018-04-06 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_waitress', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='contact',
            new_name='email',
        ),
        migrations.AddField(
            model_name='review',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
