# Generated by Django 2.0.3 on 2018-03-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_waitress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Restaurant Name',
            },
        ),
    ]
