# Generated by Django 2.0.2 on 2018-03-26 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_waitress', '0002_auto_20180326_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuItem', models.CharField(max_length=60)),
                ('menuDescription', models.CharField(max_length=400)),
                ('menuPrice', models.FloatField()),
            ],
            options={
                'verbose_name': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateTimeField()),
                ('ready', models.BooleanField(default=False)),
                ('total', models.FloatField()),
                ('orderNumber', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Order',
            },
        ),
    ]
