# Generated by Django 2.0.2 on 2018-03-26 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_waitress', '0003_menu_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dateCreated',
        ),
    ]
